# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  finger_joint_1:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  finger_joint_2:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  joint_1:  # Base rotation
    has_position_limits: true
    min_position: -3.14159
    max_position: 3.14159
    has_velocity_limits: true
    max_velocity: 2.0
    
  joint_2:  # Shoulder pitch
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57
    has_velocity_limits: true
    max_velocity: 2.0
    
  joint_3:  # Elbow pitch
    has_position_limits: true
    min_position: -2.0
    max_position: 2.0
    has_velocity_limits: true
    max_velocity: 2.0
    
  joint_4:  # Elbow roll
    has_position_limits: true
    min_position: -1.57  # -90 degrees
    max_position: 1.57   # +90 degrees
    has_velocity_limits: true
    max_velocity: 2.0
    
  joint_5:  # Wrist pitch
    has_position_limits: true
    min_position: -1.57 
    max_position: 1.57
    has_velocity_limits: true
    max_velocity: 2.0
    
  joint_6:  # Wrist roll
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57
    has_velocity_limits: true
    max_velocity: 2.0