# Originally from gpt; just a test file

planning_pipelines: ["ompl"]
pipeline_configs:
  ompl:
    planner_configs: ["RRTConnect"]
    request_adapters: >-
      default_planner_request_adapters/AddTimeParameterization
    start_state_max_bounds_error: 0.1